### ISSUE TITLE
Update teacher instructions for anonymous link

### ISSUE THREAD

**Issue by jonespm** [longhornopen/qualtrics-lti#16]
I was informed that the instructions are out of date

This should read

> In Qualtrics, this is under the ‘Distributions’ menu item.  Click ‘Anonymous Link’ in the right navigation menu, and then click ‘Copy Survey Link’

https://github.com/longhornopen/qualtrics-lti/blob/c791888b4598356e055e0a222f80271800d40b6d/web/resources/views/tool_teacher.blade.php#L59

**Comment by chrispittman** [comment]
I think these instructions are mostly correct as-is.  Qualtrics gives you a different UI sometimes, and I'm pretty sure that it's when it's the first time you create a distribution: 

![Screenshot 2023-05-08 145009](https://user-images.githubusercontent.com/918414/236920163-f50815e6-bf52-4221-84ee-174bdcbbddbc.png)

And I've been assuming that mostly these are for surveys that haven't been distributed yet, so that's the UI most end users are going to see.

I'd be happy to have some text there which'd cover both cases, but I couldn't figure out how to write it without verbally describing a big flowchart based on whether you've created a distribution yet or not, which most users aren't going to remember anyway.  In practice, all of UT Austin's users running into this have successfully gotten through to the 'Anonymous Link' based on these instructions.
